### PR TITLE
Fix: fastStatelessWrapper props check

### PR DESCRIPTION
**Pull request by etaoins**
When checking for property changes fastStatelessWrapper was checking to see if any property matched instead of all properties matching. Fix and add a test.

### CODE REVIEW

**Comment by tchcxp** [comment]
LGTM 👍

**Comment by davepoon** [comment]
LGTM :thumbsup:

**Comment by etaoins** [comment]
@tchcxp @davepoon Merge?

**Comment by tchcxp** [comment]
Merging...

**Pull request merged**
