### PR TITLE
[ADS-5010] chore: upgrade react-dev-utils to latest to fix dependabot alert

### PR DESCRIPTION
**Pull request by bchew**
## Description

Upgrade react-dev-utils to latest to fix dependabot alert

https://github.com/facebook/create-react-app/releases/tag/v4.0.3

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Harris-YWang — APPROVED** [review]
LGTM

**Review by knilink — APPROVED** [review]

**Review by pphminions — APPROVED** [review]
LGTM 🟠

**Review by romi-h — APPROVED** [review]

**Review by Harris-YWang — APPROVED** [review]
Buddy tested through local servers, docs and features looks good

**Review by xiaofan2406 — APPROVED** [review]

**Comment by pphminions** [comment]
merging 🚀

**Pull request merged**
