### PR TITLE
New: info icon popover

### PR DESCRIPTION
**Pull request by ChaoLiangSuper**
## Description

Add info icon popover component
`HelpIconPopover` and `InfoIconPopover` will share most of their code.
Add new icons

- [ ] Test and coverage

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Screenshots (if appropriate):
Screen Shot 2019-03-27 at 5 01 45 pm

## Check-list:

- [ ] I have read the [Contributing](CONTRIBUTING.md) document.
- [ ] I've thought about and labelled my PR/commit message appropriately.
- [ ] If this PR introduces breaking changes I've described the impact and migration path for existing applications.
- [ ] CI is green (coverage, linting, tests).
- [ ] I have updated the documentation accordingly.
- [ ] I've two LGTMs/Approvals.
- [ ] I've fixed or replied to all my code-review comments.
- [ ] I've manually tested with a buddy.
- [ ] I've squashed my commits into one.

### CODE REVIEW

**Comment by lightbringer1991** [comment]
what's the difference between `HelpIconPopover` and `InfoPopover`?

**Comment by ChaoLiangSuper** [comment]
@veegandhi It is a feature work request.

**Comment by ChaoLiangSuper** [comment]
@lightbringer1991 the only difference is the classname which contains the icon.
And the `InfoPopover` is not exported.

**Comment by lightbringer1991** [comment]
I think if the difference is just the class name, ideally we can expose a component called `IconPopover`, and pass in the `className` as one of the props...
I think in this PR you've already done that, but not exposing `IconPopover` component.
@veegandhi @ChaoLiangSuper any chance that we can do that instead of exposing 2 similar components?

**Comment by veegandhi** [comment]
@lightbringer1991 - I agree that should be the way to go and that is the reason this should have been in issue list to clarify on the implementation details. If we go by this approach, for every icon we have a popover, we will need another component all together.

@ChaoLiangSuper - Can you please add this item on the issue list regardless. Cheers!

**Comment by ChaoLiangSuper** [comment]
@lightbringer1991 @veegandhi The reason for exposing two components. Because the these two components are for certain case only. And I try to not make a breaking change to the PR.
Also I don't mind to pass classnames. But for a normal case, we should not encourage people to pass a certain classname for changing the background.
As a normal case, people should use <Popover /> + <SvgComponent />

**Pull request closed without merging**
