### PR TITLE
Fix: Merge Alexandria into Adslot UI

### PR DESCRIPTION
**Pull request by patrick-ivers**
#### Background
Having Alexandria and Adslot UI component libraries in separate repositories makes development slow. The aim of this PR is to merge the two repositories together, but still keep a logical separation between components. This will enable us to do a single release when making updates to either the Adslot UI or Alexandria components. This also means dependencies, scripts, and configuration can be shared.

#### Changes
- Rename variables in main to avoid naming conflicts when alexandria's Main.jsx is merged in
- Move across Alexandria component examples
- Move Alexandria dependencies to Adslot UI
- Move Alexandria components into Adslot UI
- Fix TileGrid hover state styles
- Add react key to TileGrid items to fix warnings
- Move Alexandria tests across
- Update ESLint to fix linting errors
- Update README to reflect changes

##### The burning of the Library of Alexandria
We should have foreseen this would happen...
gettyimages-599955065-e

### CODE REVIEW

**Comment by sonhanguyen** [comment]
the name is cursed

**Comment by patrick-ivers** [comment]
@omgaz What would be the advantage of that?

**Comment by vinteo** [comment]
do we still want to be able to publish `alexandria` separately to npm?

**Comment by patrick-ivers** [comment]
@vinteo Gary just mentioned that he uses Alexandria in his own stuff. I guess if it's an open-source project we need to be mindful of that. Plus, I'm not sure how Symphony are using it. It might be best to publish them separately.

**Comment by patrick-ivers** [comment]
@vinteo Unless Symphony are using Alexandria on its own, I say we don't concern ourselves with publishing separate packages.

**Comment by patrick-ivers** [comment]
FYI to anyone doing a code review on this PR. You can ignore all the files that are fully green, as they're just copied over from Alexandria. 😉

**Comment by lteacher** [comment]
merging

**Pull request merged**
