### PR TITLE
Breaking: Remove max-height from modals

### PR DESCRIPTION
**Pull request by omgaz**
We want modal heights to expand to whatever height they need and use the browser's window scroll-bar to navigate the length.

Also added an extra set of classes for spacing around modal instructions at the top.

screen shot 2016-04-14 at 11 51 24

### CODE REVIEW

**Comment by etaoins** [comment]
Simples

**Comment by etaoins** [comment]
LGTM! :rat:

**Comment by pphminions** [comment]
LGTM :bee:

**Comment by omgaz** [comment]
@etaoins @pphminions merge?

**Comment by pphminions** [comment]
Merging :rocket:

**Pull request merged**
