### PR TITLE
Update react select

### PR DESCRIPTION
**Pull request by ChaoLiangSuper**
- Update react-select to the latest.
- Will working on the migration later.

### CODE REVIEW

**Comment by xiaofan2406** [comment]
whats the plan for fixing the styling differences

**Comment by ChaoLiangSuper** [comment]
Will create a feature for demo and testing with Pedros, will work out the styling later. And will not using the old style. @xiaofan2406

**Comment by xiaofan2406** [comment]
feel like that should be part of this PR.

since it will block us from releasing/upgrading adslot-ui in direct-web/grid.

**Comment by ChaoLiangSuper** [comment]
No it will not be affected on the release, this PR will not go into master soon.

**Comment by xiaofan2406** [comment]
missed the base branch. LGTM

**Pull request merged**
