### PR TITLE
Update: wrapper for radio, checkbox

### PR DESCRIPTION
**Pull request by OndrejCholeva**
Adding wrapper to have better control over radios
and checkboxes. Currently used just for adding
data-test-selector property.

### CODE REVIEW

**Comment by vinteo** [comment]
LGTM, I assume it has been tested in `direct-web`?

**Comment by OndrejCholeva** [comment]
@vinteo it wasn't :-/ thanks for reminder.

**Comment by omgaz** [comment]
LGTM. There's been lots going on in adslot-ui land, you'll need to 

1. Rebase against master. You'll get conflicts you'll need to resolve by running…
2. `npm install` to make sure your local is up to date for when you…
3. `npm run dist` and create a new dist file
4. and mark your conflicts as resolved and `--continue`

**Comment by OndrejCholeva** [comment]
not needed.

**Pull request closed without merging**
