### PR TITLE
Build: Much fix. Many upgrade. Very coverage. Wow.

### PR DESCRIPTION
**Pull request by omgaz**
- Upgrade alexandria (tag component)
  - Remove treepicker expects that relies on an alexandria default that no longer is set
- Return coverage to 100%
  - Add accordian test for dts
  - Add panel component test for dts
  - Add tree picker tests for empty and initial states
- Fix linting warnings
- 100% coverage requirement for each component (except Main)
- Lock down react version to 15.1.0 until we have a strategy for undeclared prop types and third party components (opened an issue https://github.com/Adslot/adslot-ui/issues/281)
- Move panel dts prop type to outer most container
- Update inverse button border colours to be a tad lighter (requested by Pedros)

### CODE REVIEW

**Comment by NamrataTrivedi** [comment]
untitled

**Comment by sharmajyo** [comment]
LGTM

**Comment by patrick-ivers** [comment]
LGTM :octocat:

**Comment by mcslash** [comment]
Stupendous!

**Comment by mcslash** [comment]
@omgaz can I merge?

**Comment by patrick-ivers** [comment]
Merging. 🍜

**Comment by mcslash** [comment]
Sorry Patrick. Intercepted!

**Comment by patrick-ivers** [comment]
AGAIN!!! 😠

**Pull request merged**
