### PR TITLE
Update: TreePicker expander visible without hover

### PR DESCRIPTION
**Pull request by camjc**
#### What does this PR accomplish?
- Make the expander always visible instead of just on hover
- Give it its own cell to prevent long names hiding it.

#### How should this be manually tested?
-

#### Any background context you want to provide?
-

#### Screenshots (if appropriate)
expander

### CODE REVIEW

**Comment by tchcxp** [comment]
LGTM

**Comment by mcslash** [comment]
Seems sensible. Open that folder! :file_folder: :open_file_folder:

**Comment by vinteo** [comment]
LGTM

**Comment by OndrejCholeva** [comment]
:+1: for the icon

**Comment by pphminions** [comment]
LGTM :evergreen_tree:

**Comment by tchcxp** [comment]
Merging and happy new year! :monkey:

**Pull request merged**
