### PR TITLE
Upgrade lodash to v4

### PR DESCRIPTION
**Pull request by lteacher**
Upgrades lodash to be based off the latest version.

### CODE REVIEW

**Comment by patrick-ivers** [comment]
@lteacher Really? That's it?

**Comment by lteacher** [comment]
Seems like it...

**Comment by patrick-ivers** [comment]
@lteacher Btw, you didn't need to generate a dist because that is done with the release.

**Comment by lteacher** [comment]
@patrick-ivers actually I needed the dist because direct-web is pointing at the git branch so it doesn't run the build thats why. Will swap that out to use this on release.

**Comment by patrick-ivers** [comment]
Merging...

**Pull request merged**
