### PR TITLE
Update: SVG Symbol support for empty states

### PR DESCRIPTION
**Pull request by vinteo**
image

image

image

image

### CODE REVIEW

**Comment by camjc** [comment]
I guess you need to add svgforeverybody and do some cross browser tests too.
The icon you're adding looks too big for its circle.

**Comment by omgaz** [comment]
Does the test runner spew a bunch of web-server 404 warnings in the console, like with direct-web? If so is there a way we can mute it?

Otherwise, LGTM!

**Comment by vinteo** [comment]
svgforeverybody is bundled with alexandria and should run with it. Tested with IE, it works

no 404 errors

**Comment by vinteo** [comment]
@camjc @omgaz merge?

**Comment by camjc** [comment]
merging!

**Pull request merged**
