### PR TITLE
New: Treepicker totals suffix

### PR DESCRIPTION
**Pull request by camjc**
- Can pass a totalsSuffix to TreePicker for display.

screen shot 2016-02-26 at 3 35 50 pm

### CODE REVIEW

**Comment by pphminions** [comment]
LGTM :hocho:

**Comment by OndrejCholeva** [comment]
Looks a bit weird to me (like a currency). Can it be suffix of the label instead?

**Comment by omgaz** [comment]
Should this not just be part of the valueFormatter?

**Comment by camjc** [comment]
@OndrejCholeva It needs to be linked stronger to the pricing. Design and product teams have looked at heaps of alternatives and this is the best so far. It may change in the future.

@omgaz Nope, we only want to show it in totals, not on every node.

**Comment by omgaz** [comment]
Merging :ramen:

**Pull request merged**
