### PR TITLE
New: FormGroup, Radiogroup-stacked

### PR DESCRIPTION
**Pull request by camjc**
screen shot 2016-03-18 at 3 10 58 pm
screen shot 2016-03-18 at 4 07 04 pm

### CODE REVIEW

**Comment by vinteo** [comment]
LGTM

**Comment by omgaz** [comment]
We need to bring all field components in line, will check it out on Monday

**Comment by camjc** [comment]
Updated and updated screenshots, check it @omgaz

**Comment by omgaz** [comment]
lgtm, merging

**Pull request merged**
