### PR TITLE
Update: tree picker options to hide search on root

### PR DESCRIPTION
**Pull request by Maxmus1989**
out

### CODE REVIEW

**Comment by lightbringer1991** [comment]
@omgaz could you please take a look at this one. Looks like what we're trying to achieve in the audience survey segment picker

**Comment by omgaz** [comment]
Can you give some more detail? Which other picker and what is the goal? Sorry, been away a bit and forget.

**Comment by lightbringer1991** [comment]
@omgaz the hide search on the survey request one

**Comment by omgaz** [comment]
LGTM. Pedros and I need to go through our component library when i get back and solidify the UX patterns we want to adopt. I feel like this should always just be the default behaviour - but maybe cases where not.

**Comment by vinteo** [comment]
Merging...

**Pull request merged**
