### PR TITLE
add popover to tree picker button

### PR DESCRIPTION
**Pull request by glenkurniawan-adslot**
## Description

Add popover to the tree picker add (+) and remove (-) button

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by vinteo — DISMISSED** [review]

**Review by pphminions — APPROVED** [review]
LGTM ⏸️

**Review by xiaofan2406 — APPROVED** [review]

**Comment by glenkurniawan-adslot** [comment]
@vinteo @pphminions re-cr please, xiaofan asked that we use conditional rendering.. thanks

**Review by vinteo — APPROVED** [review]

**Review by pphminions — APPROVED** [review]
LGTM ⏸️

**Comment by pphminions** [comment]
merging 🚀

**Pull request merged**
