### PR TITLE
Fix: Alignment for RadioGroup Stacked in forms

### PR DESCRIPTION
**Pull request by vinteo**
image

### CODE REVIEW

**Comment by mcslash** [comment]
LGTM.

**Comment by pphminions** [comment]
LGTM ☔

**Comment by alextkachuk** [comment]
LGTM :+1:

**Comment by mcslash** [comment]
@vinteo can i merge?

**Comment by vinteo** [comment]
@mcslash yes

**Comment by mcslash** [comment]
Merged! 🚀

**Pull request merged**
