### PR TITLE
Update: item id type to any

### PR DESCRIPTION
**Pull request by tchcxp**
This PR updates the item id type from `number` to `any`, as the id can be a numeric or UUID string.

### CODE REVIEW

**Comment by pphminions** [comment]
LGTM 🌂

**Comment by omgaz** [comment]
LGTM

**Comment by omgaz** [comment]
Merging 🍜

**Comment by etaoins** [comment]
LGTM

**Comment by omgaz** [comment]
LGTM, happy to merge :)

**Pull request merged**
