### PR TITLE
[ASC-115] fix: new spinner size

### PR DESCRIPTION
**Pull request by superpower1**
## Description

1. Change spinner medium size to 30x30px
2. Change spinner large size to 40x40px
3. Add className prop
4. Deprecate colourStyle prop (user can use className to give any custom styles so colourStyle is not needed)

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by Harris-YWang — COMMENTED** [review]
Talked with Haofu, we determine to add a `className` prop to <Spinner /> with this pr as if users may want to have some customized design with the component.

**Review by vinteo — APPROVED** [review]

**Review by pphminions — APPROVED** [review]
LGTM 🍏

**Review by Harris-YWang — APPROVED** [review]
LGTM

**Comment by pphminions** [comment]
merging 🚀

**Pull request merged**
