### PR TITLE
Fix: Prevent .has-error from applying style to FilePicker

### PR DESCRIPTION
**Pull request by patrick-ivers**
#### Changes
- Override red border that gets applied to filepicker input when ancestor node is .has-error. Error styles are already applied to .filepicker-component-highlight class, but ancestor may need to have .has-error class to apply style to the error text that appears under the filepicker.

#### Trello
https://trello.com/c/QzEQfuMa/5630-creative-file-upload-error-messages-2d

##### OLD
screen shot 2016-09-20 at 11 50 44 am

##### NEW
screen shot 2016-09-20 at 11 50 28 am

### CODE REVIEW

**Comment by omgaz** [comment]
The red colour doesn't look right, but could be an artifact of the screenshot. Is it #d5382e?

**Comment by omgaz** [comment]
LGTM

**Comment by patrick-ivers** [comment]
@omgaz. Yes, it is `#d5382e`

**Comment by OndrejCholeva** [comment]
LGTM merging 🚀

**Pull request merged**
