### PR TITLE
Update: TreePicker move alert, remove `cost` label

### PR DESCRIPTION
**Pull request by camjc**
- Move the required/warning alert to the top.
- Remove the `cost` label from the header,
  this was accidentally never exposed, so this
  is not a breaking change.

### CODE REVIEW

**Comment by etaoins** [comment]
LGTM :alarm_clock:

**Comment by vinteo** [comment]
LGTM

**Comment by omgaz** [comment]
LGTM

**Comment by camjc** [comment]
Tested with Ondrej.

**Comment by vinteo** [comment]
Merging...

**Pull request merged**
