### PR TITLE
Fix: File upload button

### PR DESCRIPTION
**Pull request by patrick-ivers**
#### Changes
- Add styles back to file upload and elements styled as buttons (but aren't actually buttons), by changing style selector from `:enabled` to `:not(:disabled)`

#### Trello
https://trello.com/c/JooIv3Ud/5489-inverse-button-styled-elements-style-is-broken-3h
https://trello.com/c/bmd0ibrR/5490-filepicker-remove-button-style-is-broken

### CODE REVIEW

**Comment by vinteo** [comment]
LGTM

**Comment by vinteo** [comment]
Actually should we include some of the different styles in Main.js so we can see if it breaks again?

**Comment by OndrejCholeva** [comment]
As for the https://trello.com/c/bmd0ibrR/5490-filepicker-remove-button-style-is-broken - I think the issue there is more about wrong classes being used for the [X] button, so even though this PR would make it appear right, it is not the right fix.

**Comment by omgaz** [comment]
@OndrejCholeva Yea, the file-picker issue is now more of a technical-debt refactor issue now. I can update that card so the fix and issue is apparent.

**Comment by patrick-ivers** [comment]
@vinteo I can definitely do that, but some of the file picker styles (specifically the styles that make the actual button hidden) are applied on a case by case basis in direct-web. As such, a file picker in adslot-ui would not look quite right, despite having the correct button styles.

**Comment by omgaz** [comment]
@patrick I think @vinteo just means to add an adslot-ui <a href> and <span> with classes .btn and make sure they look correct

**Comment by patrick-ivers** [comment]
@omgaz Ah! 😝

**Comment by omgaz** [comment]
LGTMerging 🐏 🐟

**Pull request merged**
