### PR TITLE
Fix: TreePicker delete selected rootType on empty

### PR DESCRIPTION
**Pull request by camjc**
- Accidentally used the active rootType instead of
  the deleted node's rootType. This caused the active
  rootType to be emptied when any other rootType had
  its last node removed.

### CODE REVIEW

**Comment by OndrejCholeva** [comment]
LGTM :ski:

**Comment by omgaz** [comment]
LGTM :fish_cake:

**Comment by vinteo** [comment]
LGTM

**Comment by vinteo** [comment]
Merging...

**Pull request merged**
