### PR TITLE
[ASC-121] chore: replace usage of 'colour' with 'color' in comments/docs

### PR DESCRIPTION
**Pull request by renrizzolo**
## Description
For consistency with css properties, replace all usage of `colour` with `color`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by adityasabnis — APPROVED** [review]

**Review by pphminions — APPROVED** [review]
LGTM 🦋

**Review by Harris-YWang — APPROVED** [review]
LGTM, as talked for the task card ASC-121

**Review by vinteo — APPROVED** [review]

**Review by superpower1 — APPROVED** [review]

**Review by knilink — APPROVED** [review]

**Review by bchew — APPROVED** [review]

**Review by lightbringer1991 — APPROVED** [review]
LGTM

**Comment by vinteo** [comment]
Merging...

**Pull request merged**
