### PR TITLE
Build: When running dist create an unminified copy

### PR DESCRIPTION
**Pull request by omgaz**
- Split the dist file (non-breaking change)
- CSS is tricky, haven't been able to accomplish it
- Export Tag component (missed in last PR)
- Remove redundant (implied) 'loader' from loaders

### CODE REVIEW

**Comment by OndrejCholeva** [comment]
do we need to include `dist/adslot-ui-main-ugly.js` into commit?

**Comment by omgaz** [comment]
That's the purpose of the commit... so that it get's generated because we can't validate if a minified copy is valid otherwise.

**Comment by pphminions** [comment]
LGTM 🍒

**Comment by vinteo** [comment]
LGTM

**Comment by vinteo** [comment]
Merging...

**Pull request merged**
