### PR TITLE
[ASC-107] feat: add target to button

### PR DESCRIPTION
**Pull request by Harris-YWang**
## Description

Add a new prop 'target' to `<Button />` which provides a way to open a new page in a blank tab, for example

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by vinteo — APPROVED** [review]

**Review by glenkurniawan-adslot — APPROVED** [review]

**Comment by glenkurniawan-adslot** [comment]
@Harris-YWang is it worth to create an example for target other than self (the default)?

**Comment by Harris-YWang** [comment]
> @Harris-YWang is it worth to create an example for target other than `_self` (the default)?

I can make one as if you want it

**Comment by glenkurniawan-adslot** [comment]
> > @Harris-YWang is it worth to create an example for target other than `_self` (the default)?
> 
> I can make one as if you want it

It's up to you.. or maybe ask the others.. @superpower1

**Review by superpower1 — APPROVED** [review]

**Comment by vinteo** [comment]
Merging...

**Pull request merged**
